controller_manager:
    ros__parameters:
        update_rate: 1000
        use_sim_time: true

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        position_controller:
            type: position_controllers/JointGroupPositionController

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController

        dummy_controller:
            type: position_controllers/JointGroupPositionController

position_controller:
    ros__parameters:
        joints:
            - left_steer_joint
            - right_steer_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity

velocity_controller:
    ros__parameters:
        joints:
            - back_left_axle_joint
            - back_right_axle_joint
        interface_name: velocity
        command_interfaces:
            - velocity
        state_interfaces:
            - position
            - velocity

dummy_controller:
    ros__parameters:
        joints:
            - front_left_axle_joint
            - front_right_axle_joint
            - trailer_joint
            - trailer_left_axle_joint
            - trailer_right_axle_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
