controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        dummy_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
    ros__parameters:
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
            - joint_6
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position

dummy_controller:
    ros__parameters:
        joints:
            - link_1_cap_joint
            - link_2_cap_joint
            - link_3_cap_joint
            - link_4_cap_joint
            - link_5_cap_joint
            - link_6_cap_joint
            - tooling_joint
            - link_2_cap_2_joint
            - link_2_cap_1_joint
        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
